### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by montes2012** [amranidev/scaffold-interface#1]
@Amrani Interesting,

testing, http://crud/scaffold/guipost

I get MethodNotAllowedHttpException in RouteCollection.php line 219:

**Comment by amranidev** [comment]
thank you for your testing.

usually you're using a virtual hosting such like MAMP or LARAGON,

please check your vortualhost configuration.

**Comment by MikeCase** [comment]
I got the same thing, I'm not using virtual hosting... I don't believe it's pulling the resources, views, routes, controllers etc.. Maybe I'm just doing something wrong the last time I used laravel it was version 4.2 :P

**Comment by challapradyumna** [comment]
![capture](https://cloud.githubusercontent.com/assets/838556/13752227/c8e98964-ea33-11e5-9ea2-8f4c12597fb9.PNG)

I am getting a 301 redirect to a link without the public folder

**Comment by challapradyumna** [comment]
I have changed the hardocded url in the custom.js to fit my url structure  but somehow a trailing slash is being added to the url which is not there in custom.js . 
That trailing slash is causing the 301 redirect . If i remove that i am able to post .

**Comment by amranidev** [comment]
the slash was removed from custom.js in the newest version v1.2.x
which version of scaffold interface that have you are running ?

**Comment by amranidev** [comment]
Thank You @challapradyumna !! :+1: 
I got it.
I thought that I was remove it !!
