### ISSUE TITLE
sqlite problem in creating relationship fields

### ISSUE THREAD

**Issue by ngutip** [amranidev/scaffold-interface#10]
sorry for the earlier post about this topic, i ididn't check the ajax request, it get  http status 500, it 's turn out that sqlite doesn't recognize "show columns from `tbl_name`;" command, the getResult() method in autoarray class, cannot use getAttributes().
so i use Schema::getColumnListing($table) instead to get list of column

**Comment by amranidev** [comment]
@ngutip Greate!!

did you try the latest version v1.3.4 ??

**Comment by amranidev** [comment]
check v1.3.25

big thanks for you @ngutip 

Cheers !!
