### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by GoodJob** [amranidev/scaffold-interface#101]
Guys, this is product of the future! Please keep improving. I even would pay for it :) 

But this time, I want to ask about tables naming convention. I have create tale `category_descriptions`, so expected controller should be CategoryDescriptionsController.php and model `CategoryDescription.php`, but I have got `Category_descriptionController.php`, so everything went not so well -routes, views and so on. I think naming convention should be first words always in singular expression and the last one in plural, as in Ruby on Rails. And Maybe camel-case?

Thanks thanks thanks :)

**Comment by amranidev** [comment]
@GoodJob 

Thanks!!, I really appreciate your feedback!!
The **TableName** filed in the interface doesn't refer to a (**database table**), so in the next version it would be changed to **EntityName** or **ClassName**. 

Let's say we want to create a new entity called **Client**

1. Generate your (`Client`) entity in the interface.
2. Before migrating (`clients`) schema, you can change table name in migration file.
3. Now you must override table name in Model
 ```php
 protected $table = 'myclients';
 ```
4. Finally, migrate the schema.

Feel free to submit any issue or pull request!!

**Comment by GoodJob** [comment]
Thanks for your explanation! I will do some experiments on this :) Good luck
