### ISSUE TITLE
ManyToMany.php bug

### ISSUE THREAD

**Issue by twoheadedmona** [amranidev/scaffold-interface#102]
Hello

You have a little bug in your ManyToMany.php class. You forget to include "<?php\n\n" in your view template, and the migration file that is created does not include <?php so it can't be migrated to database unless you manually add it. I modified your ManyToMany.php :
`$migrationContent = "<?php\n\n".view('scaffold-interface::template.ManyToMany.migration', $this->tables)->render();`

Maybe update your repo for future users :)

**Comment by amranidev** [comment]
What version of scaffold-interface do you have??
It's already exist : [ManyToMany](https://github.com/amranidev/scaffold-interface/blob/master/src/ManyToMany/ManyToMany.php#L79)
