### ISSUE TITLE
Unable to execute migration step on new install

### ISSUE THREAD

**Issue by davejal** [amranidev/scaffold-interface#110]
Followed step 1-3 without problems

On step 4 I get the following error:

```

> [Illuminate\Database\QueryException]
> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
> oo long; max key length is 767 bytes (SQL: alter table `users` add unique `
> users_email_unique`(`email`))
> 
> 
> 
> [PDOException]
> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
> oo long; max key length is 767 bytes

```

I have installed this scaffold-interface many times without problems and this time I'm installing it again, but it's given this problem so many time now.

**Comment by davejal** [comment]
This is a laravel 5.4 issue according to https://github.com/laravel/framework/issues/17508

**Comment by davejal** [comment]
Update your **`app\Provider\AppServiceProvider.php`** to;

`<?php

namespace App\Providers;

use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
       Schema::defaultStringLength(191); //
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}`

**Comment by amranidev** [comment]
@davejal 
What was the problem ??
Is this package works perfectly for you ??
