### ISSUE TITLE
Little Bug - only comparing first char

### ISSUE THREAD

**Issue by osthafen** [amranidev/scaffold-interface#112]
Hi Amrani,
thanks for your project - I love it!

I think I found a little bug: Because of the [0] this function compares only the first char of each string - so two table names with equal first letters would return true.

`private function check(array $request)
    {
        return $request['table1'][0] == $request['table2'][0] ? true : false;
    }`

it should be:

`private function check(array $request)
    {
        return $request['table1'] == $request['table2'] ? true : false;
    }`

[https://github.com/amranidev/scaffold-interface/blob/master/src/Http/Controllers/GuiController.php#L275](https://github.com/amranidev/scaffold-interface/blob/master/src/Http/Controllers/GuiController.php#L275)

**Comment by amranidev** [comment]
@osthafen 

Fixed in [(v1.7.1)](https://github.com/amranidev/scaffold-interface/releases/tag/v1.7.1) 

Thank you so much for your request, I really appreciate it.

cheers!!
