### ISSUE TITLE
vinkla/pusher requires php 7

### ISSUE THREAD

**Issue by jwjcmw** [amranidev/scaffold-interface#113]
An update in the docs may be in order, as it looks like the vinkla/pusher package is not supporting 5.6.

**Comment by joransrb** [comment]
i noticed this to, and i have phpv7 installed, but it still dont work.
php -v gives:
`PHP 7.0.15 (cli) (built: Jan 23 2017 15:06:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies`

and running the composer require amranidev/scaffold-interface command gives this:
`Using version ^1.7 for amranidev/scaffold-interface
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework (locked at v5.4.15, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.15].
    - vinkla/pusher 2.5.0 requires php ^7.0 -> your PHP version (5.6.28) does not satisfy that requirement.
    - amranidev/scaffold-interface v1.7.0 requires vinkla/pusher ^2.4 -> satisfiable by vinkla/pusher[2.4.0, 2.5.0].
    - amranidev/scaffold-interface v1.7.1 requires vinkla/pusher ^2.4 -> satisfiable by vinkla/pusher[2.4.0, 2.5.0].
    - Conclusion: don't install vinkla/pusher 2.4.0
    - Installation request for amranidev/scaffold-interface ^1.7 -> satisfiable by amranidev/scaffold-interface[v1.7.0, v1.7.1].


Installation failed, reverting ./composer.json to its original content.`

**Comment by jwjcmw** [comment]
It looks like composer is using 5.6...that also happened to me.  I'm using wtserver on windows, and the composer.bat file that it creates was hard coded to using the 5.6 version.  Probably a similar issue for you.

**Comment by joransrb** [comment]
ah, thanks, did not think of that.
Fixed it now by adding correct php version in my /.bash_profile

**Comment by amranidev** [comment]
Hi Guys :smile: 

vinkla/pusher is not longer supporting php 5.6

@jwjcmw feel free to submit any issue or pull request at [scaffold-interface-docs](https://github.com/amranidev/scaffold-interface-docs) 

Thanks for opening this issue

cheers!!

**Comment by amranidev** [comment]
Updated!! 
check scaffold-interface docs [#1](https://github.com/amranidev/scaffold-interface-docs/pull/1)

cheers !!
