### ISSUE TITLE
this project is not working?

### ISSUE THREAD

**Issue by abellee** [amranidev/scaffold-interface#115]
I have installed and go into the site,
and I have created a table and some columns,
but I didn't see any changing.
so I tried to make migration, but still not change any files or database,
and I didn't see any request in network when I create table and columns,
just when I do make migration, and it just redirect to the scaffolder page,
and shows me nothing to migrate.

**Comment by amranidev** [comment]
Hi @abellee 
seems like you didn't create any table,
Make sure that you clicked on ready and done button

**Comment by abellee** [comment]
@amranidev I have clicked the READY button, and then animated a DONE button that I haven't clicked, and it would slide out a while.
so I don't know whether did wrong?

**Comment by amranidev** [comment]
you have to click on DONE button to confirm the process

**Comment by amranidev** [comment]
@abellee  All good now??

**Comment by abellee** [comment]
@amranidev sorry, didn't try yet, I'm trying to use the `Laravel Schema Designer`, but it really makes me crazy. I am gonna try your again right now.
