### ISSUE TITLE
Associate Permission with role

### ISSUE THREAD

**Issue by network211** [amranidev/scaffold-interface#119]
Hi,

Does the scaffold interface have the ability to associate a permission with a role?

It seems that spatie/laravel-permission has this built in, e.g.

$role->givePermissionTo('edit articles');

This would make your scaffold interface more complete.

**Comment by network211** [comment]
I see you have had a previous issue with the same concept (#93).

Are you planning to implement this?

**Comment by amranidev** [comment]
@network211 

According to spatie/laravel-permission, you can associate a permission with a role 
using `givePermissionTo()` method, for example :
`$role->givePermissionTo('edit articles');`

if you have any suggestion, feel free to submit it with a comment  below.

cheers!!
