### ISSUE TITLE
Lists method does not exist

### ISSUE THREAD

**Issue by Jeroen-G** [amranidev/scaffold-interface#12]
In GuiController at line 33:
```php
$scaffoldList = Scaffoldinterface::all()->lists('tablename');
```
The lists method does not exist.

**Comment by amranidev** [comment]
Weird !!

I think it's an Illuminate\Database\Eloquent\Model laravel bug.

please check your laravel version.

**Comment by Jeroen-G** [comment]
From Illuminate\Support\Collection:
`@deprecated since version 5.2. Use the "pluck" method directly.`
It originally was an alias for the pluck() function.
