### ISSUE TITLE
permissions GUI incomplete

### ISSUE THREAD

**Issue by qcol** [amranidev/scaffold-interface#124]
Hi

First of all - very good job! - the best Laravel Generator I've tested (tested all available) :)
One thing, however, wonders me. Why is GUI for permissions not completed? Creating roles and permissions without the possibility of combining them does not make sense. This module looks incomplete. Of course I know that you can do this outside the GUI but if you said A, you have to say B :)

**Comment by amranidev** [comment]
Hi @qcol 

Thanks for submitting this issue I really appreciate it.

You can combine roles and permissions by yourself according to your app logic in RolesController and PermissionController.

Otherwise if you have a feature idea you're free to submit any issue so we could talk.

Thanks
