### ISSUE TITLE
wrong constants names

### ISSUE THREAD

**Issue by qcol** [amranidev/scaffold-interface#125]
Default, in .env file is:
```
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
```
..but in application:
in app.blade.php:
```
env("PUSHER_KEY")
```
in config/pusher.php
```
env('PUSHER_KEY')
env('PUSHER_SECRET')
```

so, it doesn't work...

**Comment by amranidev** [comment]
@qcol Thanks for submitting this issue, it fixed!!

**Comment by qcol** [comment]
also in the DOC:
http://amranidev.me/scaffold-interface/docs/pusher/
