### ISSUE TITLE
How can I have custom Routes for User?

### ISSUE THREAD

**Issue by PankajSanam** [amranidev/scaffold-interface#127]
I noticed that you have routes defined in your folder which is in vendor for us.

You have routes like this-

Route::get('users', '\App\Http\Controllers\ScaffoldInterface\UserController@index');

But I want to use my own routing structure.

Am I missing something here? Because I can't seem to find a way for using my own routes and disable yours. The only way I can see here is changing the file in vendor folder, which is wrong.

**Comment by amranidev** [comment]
Hi @PankajSanam 
Thanks for submitting this issue.
Perhaps it would be more flexible to customize these routes in the next release, so I'm gonna add the enhancement tag to this to be updated.

**Comment by PankajSanam** [comment]
Ok great, thanks!

Any idea when is the next release coming?

**Comment by amranidev** [comment]
The next couple of days, I'll let you know about the updates.
feel free to submit any issue or pull request.

**Comment by amranidev** [comment]
@PankajSanam 

v1.7.15 is released, now you could update scaffold-interface in your project and you're free to customize your routes however you like, scaffold-interface routes are served under `scaffold-` prefix.

Thanks
