### ISSUE TITLE
Error with Views

### ISSUE THREAD

**Issue by ManuSbd** [amranidev/scaffold-interface#13]
Hi,

I install your package and I got some problems with views.

I see vars like : {{errorMsg}} , {{final.table}}, {{final.onData}}, {{element}} ...

And actions buttons (new, remove, more, back...) are not working

Maybe I need to install some pacakges to make it work?

Thanks.

**Comment by amranidev** [comment]
Make sure that you're connecting to the internet because the package get VueJs cdn.

**Comment by ManuSbd** [comment]
Hey!,

thanks for your reply.

The error was in the file scaffoldApp.blade.php
    <link rel="stylesheet" type="text/css" href="css/scaffold-interface-css/main.css">
    <script src = "js/AjaxisMaterialize.js"></script>
    <script src = "js/scaffold-interface-js/main.js"></script>

I remove the slash ("/") before each of local included files dir

I don't know if it's caused by my server configuratiion or something but this solve my problem i will test the app after classes.

Thanks again.

**Comment by amranidev** [comment]
@ManuSbd 
it's fixed : check v1.3.13
Cheers

**Comment by ManuSbd** [comment]
Hi again,

You're right with version 1.3.13 it works fine but this command:

> composer require Amranidev/scaffold-interface:1.3.*

Installs versión 1.3.12

Another trouble I found when u try to install the package in an existing laravel project
before execute this command:

> $ php artisan vendor:publish

I have to clear the cache with this command because I was getting an error publishing

> $ php artisan cache:clear

Thanks

**Comment by ManuSbd** [comment]
Hi,

I don't know if i should open a new issue.

I have problems with modal links.

1.- Modal opened when rollback (scaffoldApp.blade.php line 129)

2.- Modal opened when delete row (controller.blade.php line 175)

The data-link parameter is not getting {{URL::to('/')}}, but if I put it on the link the url is not correct the only way I can solve this 2 problems is including
/projectname/public/ before the route existing in data-link

After this a couple of enhacing features could be:

1.- Insert new rows on existing tables

2.- Rows options (nullable, max length...)

Thanks 4 all.

**Comment by amranidev** [comment]
Whoops !

@ManuSbd Gracias man :smile: 

### About Modals

You're certainly install that package to a deployed app on a web server right ??
so `{{URL::to('/')}}` returns to the main root : `example.com/`  instead `example.com/projectname/public/`
well you got a problems with links.
I think you should change `{{URL::to('/')}}` to `{{URL::to(/projectname/public/)}}`

Anyway I think it's need some enhancements to create new config file to set different variables for links and others . . . .

### About OneToMany  

Scaffold interface only covered the tables that created by itself, if you create a table a way form package, It does not recognize it.

### Enhancements

Looks like there is a lot of things to be developed. ManyToMany & languages translations.
may all these cool features could be available the next couples of weeks.

Any ideas are welcome. Feel free to submit any issues or pull requests.

Cheers !!

**Comment by ManuSbd** [comment]
Hi,

### About Modals:

The modals doesn't have {{URL::to('/')}} directly link the views. For example:

> data-link = '/scaffold/guidelete/{{$value->id}}/'


### About ManyToOne:

I was wrong writing.

I refer to ManyToOne option.

The error is that i'm using PostgreSql. In Attributes.php there are a function that retrieve table columns:

> $this->result = DB::select(DB::raw('show columns from `' . $this->table . '`;'));

In PostgreSql this doesn't work, it needs something like this

> $this->result = DB::select(DB::raw("SELECT column_name FROM information_schema.columns WHERE table_name ='".$this->table."';"));

In AutoArray.php

> if ($key == "column_name") {

With this changes i can get correct columns but still have and error i don't know why cause server is returning a 200 response.

Also I don't understand why u delete the first element of the array ( the id column )

> unset($this->result[0]);

This field is the reference what foreign key point right?

> $table->foreign('user_id')
>       ->references('id')->on('users')
>       ->onDelete('cascade');

For example this, 
user_id is the ManyToOne field that we want create.
id is the id field of table we want reference
users table we want reference
You're deleting this id from the array. What u reference?

I'm speacking without knowledge of this cause i can't test it yet cause errors.

Well thanks.

**Comment by amranidev** [comment]
@ManuSbd  

The modals has generated by [Ajaxis](https://github.com/amranidev/ajaxis) Package.
That certainly must have a baseURL to complete an ajax request. 

Check scaffoldApp.blade.php [Line : 176](https://github.com/amranidev/scaffold-interface/blob/master/resources/views/scaffoldApp.blade.php#L176)

>  var baseUrl = "URL::to('/')"

So you can change your baseURL easily.

About Removing (id column) : 
The Attribute class just return the attributes of an existing Table in database. to specify the onData
on views (select OneToMany) . . .

I think I must enhance this section to make it compatible (MySql,Postgresql,...) 

if you have any problems or errors with that package , feel free to open a issue or contact me on email.

Thank you again @ManuSbd for your reporting. 

Cheers !!

**Comment by amranidev** [comment]
@ManuSbd  Hi !!

about Attributes.php

Can you test it with "dev-master" by postgreSql 

Any suggestions are welcome !  

cheers !

**Comment by ManuSbd** [comment]
Hi,

I'm not an expert in PostgreSql database but I think you have an error here.

> table_schema ='" . env('DB_DATABASE') . "'

table_schema is not the database you are connecting. 

For example table_schema contains "public" on tables that you create.

> "SELECT column_name FROM information_schema.columns WHERE table_name ='" . $this->table . ';"

With this should be enough cause when you connect to database you can't have more than one table with same name (you don't see other databases in PostgreSql)

All of this is for PostgreSQl I don't know how works in other database at this moment.

See ya.

**Comment by amranidev** [comment]
Gotcha!!

@ManuSbd 

I fixed it.
it works fine right now.

check dev-master

Cheers !!

**Comment by amranidev** [comment]
@ManuSbd 

check the v1.3.20
It fixed, I have test it with Postgre and it works fine. 

Cheers !!

**Comment by ManuSbd** [comment]
![image](https://cloud.githubusercontent.com/assets/18328695/14669209/24c82148-06e8-11e6-83f4-a41970b77c7c.png)

Hi, Now i'm not getting error with parameters but they don't appear in combobox.

**Comment by amranidev** [comment]
Whoops !!

it's weird !!! 

make sure that posts2s already has attributes :laughing:

I've been  test it  with postGres and it works fine.

Any suggestion ?

**Comment by amranidev** [comment]
Gotcha !!

I just replace all DB query with `Schema::getColumnListing` to make it global with other databases 

check v1.3.25

big thanks for you @ManuSbd 

Cheers !!
