### ISSUE TITLE
"Trying to get property of non-object" exception

### ISSUE THREAD

**Issue by gitxav** [amranidev/scaffold-interface#130]
Hi Amrani.

I created a blog application in Laravel 5.4 and followed all the steps in the tutorial and successfully created a Post table, but when going to http://blog/post it throws the exception error:
```
Trying to get property of non-object (View: /var/www/html/laravel/blog/resources/views/scaffold-interface/layouts/app.blade.php) (View: /var/www/html/laravel/blog/resources/views/scaffold-interface/layouts/app.blade.php)
```
Thanks for your help

**Comment by amranidev** [comment]
@gitxav 
Thanks for submitting this issue.
You have to create a new user and login with its account.
Thanks!!
