### ISSUE TITLE
ErrorException while creating a row of data 

### ISSUE THREAD

**Issue by jeremywhx** [amranidev/scaffold-interface#134]
When I submit a created data, it pops out Call to undefined method Illuminate\Database\Query\Builder::render() (View: C:\xampp\htdocs\asiana_dev\resources\views\news\index.blade.php)

**Comment by amranidev** [comment]
@jeremywhx 
Thanks for submitting this issue.
Which laravel version do you have ??

**Comment by jeremywhx** [comment]
5.4
