### ISSUE TITLE
fill new table errors

### ISSUE THREAD

**Issue by jorjik** [amranidev/scaffold-interface#136]
(3/3) ErrorException
Trying to get property of non-object (View: D:\php\OpenServer\domains\lava\blog\resources\views\scaffold-interface\layouts\app.blade.php) (View: D:\php\OpenServer\domains\lava\blog\resources\views\scaffold-interface\layouts\app.blade.php)

(2/3) ErrorException
Trying to get property of non-object (View: D:\php\OpenServer\domains\lava\blog\resources\views\scaffold-interface\layouts\app.blade.php)

(1/3) ErrorException
Trying to get property of non-object

in 8419f0d3f3f8c20cb024e94a862960099ac86cc6.php (line 65)

**Comment by amranidev** [comment]
Normally this is happened because of the user property object.
go to `localhost:9000/login` and try to login or register a user account.

**Comment by jorjik** [comment]
Error 403 

> Access forbidden!
> You don't have permission to access the requested object. It is either read-protected or not readable by the server.

**Comment by amranidev** [comment]
@jorjik Hi again
I checked and everything is working as expected. well, could you please tell where you got that error exactly.

Thanks

**Comment by jorjik** [comment]
The decision to use port 9000 was an error!!!

**Comment by amranidev** [comment]
so shall I close this issue ?
