### ISSUE TITLE
erron on migrate

### ISSUE THREAD

**Issue by waltex** [amranidev/scaffold-interface#139]
i run `php artisan migrate` and return this error.
create only 2 table, migrations and users.
i use mysql with php 7.1 on xampp

 

 **error:**
> [Illuminate\Database\QueryException]                                         
>   SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
>   oo long; max key length is 767 bytes (SQL: alter table `users` add unique `  
>   users_email_unique`(`email`))                                                
>                                                                               
>                                      
>   [PDOException]                                                               
>   SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
>   oo long; max key length is 767 bytes

**Comment by amranidev** [comment]
@waltex Thanks for submitting this issue.

This is a laravel DB issue, Laravel 5.4 had a new default database character sets supporting emoji.

See : [Laravel 5.4 Specified key was too long error (laravel-news)](https://laravel-news.com/laravel-5-4-key-too-long-error)
