### ISSUE TITLE
[Proposal] Search like Gii 

### ISSUE THREAD

**Issue by marcelosantos89** [amranidev/scaffold-interface#140]
It would be great to have a search field on top like Gii 
![image](https://user-images.githubusercontent.com/5165063/29742169-0650ac4e-8a72-11e7-82be-1c1bdddf973f.png)

I'm working on it right now but still trying to understand the code

**Comment by amranidev** [comment]
Thanks for submitting this issue @orien2k 
this would be a cool new feature, I suggest to use (data-table)[https://datatables.net/]!
what do you think ?

**Comment by orien2k** [comment]
Datatables get slow if u have more than 500 rows. It needs to be with PHP no JS

**Comment by amranidev** [comment]
A'right, I'll be waiting for your pull request, let me know if you have any question!!

**Comment by Muhammadinaam** [comment]
Hi, this is a nice package but I think that the developers have stopped working on it. Maybe you can try this package: https://github.com/Muhammadinaam/speed-admin. It supports Laravel 8+.
