### ISSUE TITLE
"Prefix" on views and controllers

### ISSUE THREAD

**Issue by oalencar** [amranidev/scaffold-interface#145]
Hi, Amrani.

I want to know if theres a way to generate the views with a prefix, like “admin”, for example.

The point is, I have a lot of manual work to migrate the scaffold views to my project architecture.

Can you help? Thanks #

**Comment by amranidev** [comment]
Which scaffold-interface version do you have ??

**Comment by oscaralencar** [comment]
v1.7.21

**Comment by oscaralencar** [comment]
If don't exists a way to do it, I have an idea:

The prefix config can be saved on config.php file and the views and controllers can be generated with it.

I have made tests in my local with this approach, and worked well. A can pull request.

**Comment by amranidev** [comment]
Yeah sure, let me know when you finish.
cheers!!

**Comment by oscaralencar** [comment]
Hi, Amrani. I've tested your setting on config.php called: "loadViews". I realize that this generates the path of views on controllers with a pattern like this: "::" (four dots).

Why did you use :: ?

The implementation is on file /ROOT/scaffold-interface/resources/views/template/controller/controller.blade.php

**Comment by amranidev** [comment]
loadViews is used as a prefix to separate between laravel's default structure and your custom package.
This will be defined in the package's ServiceProvider as well.
Typically, we use LoadView when we want to generate CRUD for our customized packages, see [Lpackager](https://github.com/amranidev/lpackager).

**Comment by oalencar** [comment]
How promised, the PR #155 =D

**Comment by amranidev** [comment]
Merged! Thanks!
