### ISSUE TITLE
http://amranidev.me/scaffold-interface/docs is offline

### ISSUE THREAD

**Issue by osthafen** [amranidev/scaffold-interface#146]
No content on http://amranidev.me/scaffold-interface/docs

**Comment by amranidev** [comment]
Hi @osthafen 
Thanks for reporting
Cheers!!

**Comment by amranidev** [comment]
The docs are located in : [Docs](https://amranidev.github.io/scaffold-interface/docs)

**Comment by amranidev** [comment]
Thanks for opening this issue!!
