### ISSUE TITLE
Version conflict in resources/views/scaffold-interface/layouts/app.blade.layout

### ISSUE THREAD

**Issue by babakbandpey** [amranidev/scaffold-interface#147]
Hi dear developers.
There is some conflict leftovers at the end of the file

https://github.com/amranidev/scaffold-interface/blob/master/src/Publishes/Views/scaffold-interface/layouts/app.blade.php

HEAD
							<a href="#">\
											<i class="fa fa-users text-aqua"></i> '+data.message+'\
							</a>\

				<a href="#">\
					<i class="fa fa-users text-aqua"></i> '+data.message+'\
				</a>\

 36e331d580b33e2ad155aae685046a239e096ca2

**Comment by amranidev** [comment]
@babakbandpey Thanks for submitting this issue I really appreciate it.
Thanks!!

**Comment by amranidev** [comment]
The problem has been fixed, you could check the v1.7.24
Thanks again!!
