### ISSUE TITLE
primary key

### ISSUE THREAD

**Issue by riokurnia** [amranidev/scaffold-interface#30]
cant u make it without increments ? so we can make our primary key

**Comment by amranidev** [comment]
@riokurnia 

For sure you can change what ever you want manually, just before migrations, go to entity migration file and change primary key. then press the  migration button.

**Comment by riokurnia** [comment]
already change it but foreign key not working , "foreign key constraint is incorrectly formed" , sorry im new with laravel

**Comment by amranidev** [comment]
@riokurnia 

Check [CHANGELOG](https://github.com/amranidev/scaffold-interface/blob/master/CHANGELOG.md) release notes for v1.4.25.

You can change foreignKeys manually in migration file, then go to entity model file and override foreignKey convention.

Example:

```php
	public function customer()
	{
		return $this->belongsTo('App\Customer','customer_id');
	}
```

Cheers!!
