### ISSUE TITLE
Class web does not exist

### ISSUE THREAD

**Issue by frndchagas** [amranidev/scaffold-interface#43]
Hello, 

I am trying to install v1.4.11 for laravel 5.1.x in the [sximo5 framework.](http://sximobuilder.com/)

The error is:

`ReflectionException in Container.php line 741: Class web does not exist`

Could anyone help me?

**Comment by amranidev** [comment]
Whoops!!

@frndchagas 

go to `vendor/amranidev/scaffold-interface/src/http/routes.php` and override **web** middleware

 `Route::group(['middleware' => null])` 

cheers!!

**Comment by frndchagas** [comment]
Perfect! You're the best!

Thanks
