### ISSUE TITLE
Feature request: timestamps + softdeletes + some other columns

### ISSUE THREAD

**Issue by UnrulyNatives** [amranidev/scaffold-interface#47]
Hi, 
your package is great! I just started using it

I suggest this: 
in each table I add these columns: 

        $table->integer('creator_id')->unsigned()->nullable();
        $table->integer('updater_id')->unsigned()->nullable();
        $table->timestamps();
        $table->softDeletes();

Can you add an option to add them when treating migration? 

Thx!

**Comment by amranidev** [comment]
Yeah sure, Thanks for submitting your request.
cheers!!

**Comment by amranidev** [comment]
@UnrulyNatives 
Check [v1.5.15](https://github.com/amranidev/scaffold-interface/releases/tag/v1.5.15) 
Thank you again 
cheers !!
