### ISSUE TITLE
Laravel 5.3 compliance - route files

### ISSUE THREAD

**Issue by UnrulyNatives** [amranidev/scaffold-interface#48]
As of now your package puts the generated routes into the /App/Http/routes.php (creates a new file if there is none)

In Laravel 5.3 routes are placed in `/routes` folder. 
There are two files out of the box there: `web` and `api`. I myself have another one defined. 

The optimal way would be any of the pre-defined files or custom file to be named by user

**Comment by amranidev** [comment]
Whoops!!

You can specify routes.php location, check [config](https://github.com/amranidev/scaffold-interface/blob/master/config/config.php#L69) file.

cheers!!
