### ISSUE TITLE
form action uses hardcoded url

### ISSUE THREAD

**Issue by kirchaj** [amranidev/scaffold-interface#5]
Love what you done so far. 

I am testing your package and noticed when you generate the form method in the view you use a hardcoded url.  This will be a problem as the development is on a local machine and then will be used on a server that is not running on part 8000

<form class = 'col s3' method = 'get' action = 'http://localhost:8000/customer/create'>

**Comment by amranidev** [comment]
Whoops!
you was right. but first let me ask you a question.
do you want that url change dynamically such like {{URL::to('/')}} , instead that you could update to whatever you want ?

**Comment by kirchaj** [comment]
without a lot of thought, that would make sense.  You could always update it if it were relocated or put in a subfolder.
