### ISSUE TITLE
one to many

### ISSUE THREAD

**Issue by muuucho** [amranidev/scaffold-interface#59]
Hi!
Thanks for the CRUD generator. I can't get one2many to work
I create table citys and have a column nammed cityName.

Then when I create table members I click "One to many" I chose table citys and column cityName.
Then I generate table members and its scripts.
I expect a dropdown to show up when I want to add a member, but it doesnt.

**Comment by amranidev** [comment]
Hi! @muuucho 
Well, make sure that when you create **members** table and chose table citys and column cityName., re-click on **OneToMany** button to be confirmed.

cheers!!

**Comment by muuucho** [comment]
Thanks!

**Comment by qcol** [comment]
wow! I was sure it doesn't work too... it should be clearly explained that you have to press the onetomany button a second time, now it works in fact :)

**Comment by qcol** [comment]
would be much more intuitive button at the bottom I think
![zaznaczenie_238](https://cloud.githubusercontent.com/assets/358993/21849852/392be25e-d808-11e6-990a-f3d39f9b7cb2.png)

**Comment by amranidev** [comment]
Hi @qcol 

It's already mentioned in [documentation](http://amranidev.github.io/blog/site/scaffold-interface/#iii-relationships)
Perhaps this button should be in bottom of one-to-many field.
I really appreciate your request!!
cheers!!
