### ISSUE TITLE
delete button doesn't work

### ISSUE THREAD

**Issue by davejal** [amranidev/scaffold-interface#64]
After migrate rollback the delete button doesn't display everything, only a white bar.
![deletebutton](https://cloud.githubusercontent.com/assets/10372845/19215730/87b6d55e-8d7c-11e6-9bb2-6a9b145aed59.png)

**Comment by amranidev** [comment]
Whoops!!!
let me check :smile:

**Comment by amranidev** [comment]
Probably that you've changed something in GuiController.php,
cheers!!

**Comment by davejal** [comment]
Thanks for the response. But I started a new project with new database and still the same problem. No changes.

**Comment by davejal** [comment]
Running xampp on windows 7

Here are my versions:

Laravel installer version 1.3.1
Laravel version 5.3.18
PHP version 5.6.24
mysql  Ver 15.1 Distrib 10.1.16-MariaDB, for Win32 (AMD64)
Composer version 1.2.1

**Comment by amranidev** [comment]
Your installation is definitely correct.
Fixed!! Thanks a lot for your feedback.(v1.6.2)
Cheers!!

**Comment by davejal** [comment]
So I changed line 150 (removing the /) and tried again. Now I see the delete page confirmation, but when clicking, nothing happens.

![deletebutton](https://cloud.githubusercontent.com/assets/10372845/19216577/61c78822-8d98-11e6-92ec-a12235b0f5e7.png)

**Comment by amranidev** [comment]
@davejal 

Fixed (v1.6.3) [a6c4b1b](https://github.com/amranidev/scaffold-interface/commit/e1611db39de6f17f28c5a50a7d13e65baae2227b)

Cheers!!

**Comment by davejal** [comment]
Yes. All normal now.

**Comment by davejal** [comment]
Hi, having problems with this again. Not sure what's wrong. The confirmation page shows and the cancel button works, but the delete button does nothing.

**Comment by aboidriss** [comment]
i think  in scaffold-interface/resources/views/template/controller/controller.blade.php , function "DeleteMsg"
you should remove the last slash in  '/delete/'

**Comment by amranidev** [comment]
i'ts already removed, check the latest version :)

**Comment by aboidriss** [comment]
i don't see the modification, in which commit ?

**Comment by amranidev** [comment]
@aboidriss 

Whoops!!

You was right!!!

I Really appreciate your request/comment, 

I did not see that bug at all.

You deserve :+1:

**Comment by amranidev** [comment]
@aboidriss , @davejal 

Check the following [link](https://github.com/amranidev/scaffold-interface/commit/515318c751f7b86a24ad9f73438498f41443e676)

Cheers!!

**Comment by davejal** [comment]
Thanks now it works (after refreshing the page).
