### ISSUE TITLE
Logout button doesn't work

### ISSUE THREAD

**Issue by saviofreitas** [amranidev/scaffold-interface#65]
MethodNotAllowedHttpException in RouteCollection.php line 218.

Needs a form.

**Comment by amranidev** [comment]
Thanks!! 
btw, this not supported in laravel 5.2

**Comment by saviofreitas** [comment]
Indeed, I had not observed this point. It would be better to keep as it was and update the documentation with this solution only to version 5.3?

Can I remove the added stretch and update the documentation.

**Comment by amranidev** [comment]
@saviofreitas 

I think it would be better to upgrade it to 5.3 so we can add compatibility to docs, because laravel v5.3 is better than others.
