### ISSUE TITLE
Specify Table possible?

### ISSUE THREAD

**Issue by BinSilva** [amranidev/scaffold-interface#70]
How could I specify the table?

Example:
php artisan migrate table=schema.myTable

**Comment by amranidev** [comment]
@BinSilva 

You can specify migration path in [config/amranidev/config.php](https://github.com/amranidev/scaffold-interface/blob/master/config/config.php#L58)

If you want to specify which table check the following [link](https://laracasts.com/discuss/channels/laravel/ho-to-execute-a-specific-migration)
