### ISSUE TITLE
[Proposal] Pagination system

### ISSUE THREAD

**Issue by 7miguelsilva7** [amranidev/scaffold-interface#74]
First, congratulates for your project
Like suggestion, you can do a search and pagination system. they're welcome.

**Comment by amranidev** [comment]
Yes for sure!!

**Comment by amranidev** [comment]
Pagination is available now in  latest version [v1.6.12](https://github.com/amranidev/scaffold-interface/releases/tag/v1.6.12)

**Comment by 7miguelsilva7** [comment]
Great!
Thanks very much!
updating to version v1.6.12...
