### ISSUE TITLE
Problem to edit records with relationship

### ISSUE THREAD

**Issue by 7miguelsilva7** [amranidev/scaffold-interface#75]
Hello! First, it's a good job!
I have a problem when I am editing records with fields have relationship , the Views edit don't show me  actual records fields, it shows the first option on a select field and not a actual records in the fields recorded in database.

Could you help me to fix it?
Thanks!

**Comment by amranidev** [comment]
Hi @7miguelsilva7 

Let's say we have tow entities **Product** and **Command**, command contains a product foreign key **product_id** (OneToMany).

Go to `resources/views/command/edit.blade.php` and change product select section to.

```html
<div class="form-group">
	<label>Product Select</label>
	<select name = 'product_id' class = "form-control">
		<option value="{{$command->product_id}}">{{$command->product->name}}</option>
		@foreach($products->except($command->product_id) as $key => $value)
		<option value="{{$key}}">{{$value}}</option>
		@endforeach
	</select>
</div>
```

**Comment by 7miguelsilva7** [comment]
Hi **Amranidev**

Man, it worked.

thanks!

Sorry to ask so much. I'm a noob developer.
