### ISSUE TITLE
Getting error in Dashboard on a fresh installation

### ISSUE THREAD

**Issue by spitfire64** [amranidev/scaffold-interface#76]
After having add 2 roles to roles I switch to user in order to add roles to a user I get this error:

ErrorException in 70a34edc433640635e97bdad90b795b7c04bb18a.php line 56:
Invalid argument supplied for foreach() (View: C:\laravel\z\resources\views\scaffold-interface\users\edit.blade.php)

**Comment by amranidev** [comment]
@spitfire64 

Make sure that you add `HasRole` dependency to **User.php**

Check the following [link](http://amranidev.github.io/blog/site/scaffold-interface/#iii-control-panel-adminlte).

**Comment by spitfire64** [comment]
terrible sorry! 😌😌😌😌

MVH/Mårten Hansson 0703 - 06 71 81

2016-10-25 0:20 GMT+02:00 Amrani Houssain <notifications@github.com>:
