### ISSUE TITLE
[Proposal: Search Engine]

### ISSUE THREAD

**Issue by 7miguelsilva7** [amranidev/scaffold-interface#78]
Hi! me again.
Like suggestion you can implement a search engine.

Thanks!

**Comment by amranidev** [comment]
What do you mean by search engine, could you please be more specific!!
Thanks!!

**Comment by 7miguelsilva7** [comment]
Hi man! Sorry if I did not be clear.
I want to say something like this:

![the-search-box4](https://cloud.githubusercontent.com/assets/16270181/19867436/91fed0c6-9f82-11e6-88d1-66e7f68e14d0.jpg)

That work to search in table with relationships:
Here I see how can implement it, but I think don't work in table with relationship, I'm not sure
http://anytch.com/laravel-5-simple-get-search/ 
Thanks!

**Comment by 7miguelsilva7** [comment]
Hey man!  thank you!
I'll see the link.
Thanks again.
