### ISSUE TITLE
Javascript links are static

### ISSUE THREAD

**Issue by challapradyumna** [amranidev/scaffold-interface#8]
In index.blade.php the url for javascript links should be 

    <script type="text/javascript" src = "{{ URL::asset('js/AjaxisMaterialize.js')}}"></script>
    <script type="text/javascript" src = "{{ URL::asset('js/scaffold-interface-js/customA.js')}}"></script>

**Comment by amranidev** [comment]
@challapradyumna  it's fixed check v1.3.2
