### ISSUE TITLE
a little help with search!

### ISSUE THREAD

**Issue by 7miguelsilva7** [amranidev/scaffold-interface#82]
Hi Guy!
I've implemented a  Scout search engine in my app, using your tips, It's working partially.
I have problem with tables relationship , the search don't find records for text. In other word in table without relationships the search works well.
Could you help me, can you see what's wrong? 

**This is my Model funcionarios.php:**

`<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Scout\Searchable;
/**
 * Class Funcionario.
 *
 * @author  The scaffold-interface created at 2016-10-28 02:13:47am
 * @link  https://github.com/amranidev/scaffold-interface
 */
class Funcionario extends Model
{
	use Searchable;

  public $fillable = ['funcionarios'];
   /**
     * Get the index name for the model.
    *
     * @return string

    */
        public function searchableAs()

    {
        return 'funcionarios.index';
    }
	public function siem()
	{
		return $this->belongsTo('App\Siem','siem_id');
	}

       public function ocupacao()
	{
		return $this->belongsTo('App\Ocupacao','ocupacao_id');
	}
	
	public function pessoa()
	{
		return $this->belongsTo('App\Pessoa','pessoa_id');
	}
}
`

**and this is my FuncionariosController, just my function index:**

public function index(Request $request)

    {

    	if($request->has('funcionariosearch')){

    		$funcionarios = Funcionario::search($request->funcionariosearch)

    			->paginate(6);

    	}else{

    		$funcionarios = Funcionario::paginate(6);

    	}

    	return view('funcionario.index',compact('funcionarios'));

    }

**Comment by 7miguelsilva7** [comment]
I saw in the site Algolia, my search has no relationship, the index there show id and not text

**This is my local view :**
![sglab](https://cloud.githubusercontent.com/assets/16270181/19938465/c70f560a-a103-11e6-9721-122ab04804db.png)

**This is my Algolia site view, where relationship doesn't work**
![algolia](https://cloud.githubusercontent.com/assets/16270181/19938532/05618932-a104-11e6-83d5-7dbe80e4d498.png)

**Comment by amranidev** [comment]
I don't know what's wrong with this, you can submit an issue in Algolia repo :)

**Comment by 7miguelsilva7** [comment]
Hello! You're right!
I have solve problem, giving up use a search engine,  on this app, this my third app I tried and search box with relationships don't work, I tried  Phreeze by Jason, CRUD Genarator, and now Scaffold-interface and dont work too. But your developments help us so much. Thanks a lot. 
Your app is enought I need. Thanks again.
