### ISSUE TITLE
Error inserting into database

### ISSUE THREAD

**Issue by fndchagas** [amranidev/scaffold-interface#85]
Hi, 

I've installed [Josh Admin Template ](https://codecanyon.net/item/josh-laravel-admin-template-front-end-crud/8754542) in a fresh version of Laravel 5.3, after this, I've installed scaffold-interface.

Almost all pages works fine: index, edit, delete, show and create.

But when I try to insert a register, i receive this message:

> The mypage.com page isn’t working
> mypage.com is currently unable to handle this request.

I've tried to change this line: 

`<form method = 'POST' action = '{{url("jogador")}}'>`

to 

`<form method = 'POST' action = '/jogador/store'>`

and create this route:

`Route::resource('jogador/store','\App\Http\Controllers\JogadorController@store');`

But still not worked.
 
Can u help me?

**Comment by amranidev** [comment]
@fndchagas 
What does that error shows you??

**Comment by fndchagas** [comment]
The error just shows a page with the message that I mentioned:

> The mypage.com page isn’t working
> mypage.com is currently unable to handle this request.

**Comment by amranidev** [comment]
@fndchagas 

- Form

```html
<form method = 'POST' action = "{{url('/jogador/store')}}">
. . . .
</form>
```

- Route

```php
Route::post('jogador/store','\App\Http\Controllers\JogadorController@store');
```

Cheers!!
