### ISSUE TITLE
cannot creat one to many relationship with custom tables created

### ISSUE THREAD

**Issue by claAshish** [amranidev/scaffold-interface#87]
![laravelcrudissue](https://cloud.githubusercontent.com/assets/23328777/20087473/bd37d7ac-a59e-11e6-96a0-a6176aa29fa9.JPG)

Have adde scaffold library to my project.
Creating simple table dont have any issue, but when i tried to map one to many relationshiop its giving me error.

I can select table and column except the id but when i click ready button its removing the added column from form.

**Comment by claAshish** [comment]
Found the solution "re-click on OneToMany button to be confirm".

Please update this point in you document.

**Comment by amranidev** [comment]
@claAshish 

It's already mentioned in documentation (**Relationships - OneToMany**)

check the following [link](http://amranidev.github.io/blog/site/scaffold-interface/#iii-relationships)

(**Before ending creation, click on OneToMany button, choose product table, choose associated field and re-click on OneToMany Button again to be confirmed.**)
