### ISSUE TITLE
miss permissions of roles

### ISSUE THREAD

**Issue by ThangLuuQuoc** [amranidev/scaffold-interface#93]
Can't assign one or many permission to role

**Comment by amranidev** [comment]
@ThangLuuQuoc 

You could only assign permissions and roles to users in the system, but don't worry you can assign permissions to role using your approach, check [laravel-permission](https://github.com/spatie/laravel-permission).

Feel free to change anything in:

- `app/Http/Controllers/ScaffoldInterface/AppController.php` (Where Dashboard is rendered).
- `app/Http/Controllers/ScaffoldInterface/UserController.php` (User CRUD, assign roles-permissions).
- `app/Http/Controllers/ScaffoldInterface/RoleController.php` (Role CRUD).
- `app/Http/Controllers/ScaffoldInterface/PermissionController.php` (Permission CRUD).

A permission can be given to a role:

`$role->givePermissionTo('edit articles');`

You can determine if a role has a certain permission:

`$role->hasPermissionTo('edit articles');`

A permission can be revoked from a role:

`$role->revokePermissionTo('edit articles');`
