### ISSUE TITLE
btn delete doesn't work in this version 1.6.31

### ISSUE THREAD

**Issue by 7miguelsilva7** [amranidev/scaffold-interface#95]
When I generate a GRUD, btn delete doesn't work more, how can I downgrade to other version? can I do it?

**Comment by 7miguelsilva7** [comment]
Hey man, I've solved it, just add lines like that follow:
        </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class = 'AjaxisModal'>
        </div>
    </div>
</body>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script> var baseURL = "{{URL::to('/')}}"</script>
<script src = "{{ URL::asset('js/AjaxisBootstrap.js')}}"></script>
<script src = "{{ URL::asset('js/scaffold-interface-js/customA.js')}}"></script>
</html>
@endsection

**Comment by amranidev** [comment]
Hey @7miguelsilva7 
Which line ??

**Comment by 7miguelsilva7** [comment]
these lines:
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 
<script> var baseURL = "{{URL::to('/')}}"</script> 
<script src = "{{ URL::asset('js/AjaxisBootstrap.js')}}"></script> 
<script src = "{{ URL::asset('js/scaffold-interface-js/customA.js')}}"></script>

for me, delete btn doesn't worked, then I added the line above and work now.

**Comment by amranidev** [comment]
This bloc has been added to the layouts in v1.6.31.

**Comment by 7miguelsilva7** [comment]
I see, ok, it is that my app use layouts of laravel, and when I create other MVC this bloc doesn't added.
But it's ok now.
Thanks!
