### ISSUE TITLE
[Insight] Text files should end with a newline character - in resources/…/ManyToMany/model.blade.php, line 31

### ISSUE THREAD

**Issue by CyDoor** [amranidev/scaffold-interface#96]
**[in resources/views/template/ManyToMany/model.blade.php, line 31](https://github.com/amranidev/scaffold-interface/blob/1be119f03d02543972611b2ab3d7c866a6954755/resources/views/template/ManyToMany/model.blade.php#L31)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```php
     */
    public function remove{{ucfirst(str_singular($model))}}(${{str_singular($model)}})
    {
        return $this->{{str_plural($model)}}()->detach(${{str_singular($model)}});
    }
    
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/4c35ba52-551e-4d62-adb8-ff5199c54801/analyses/378)_

**Comment by amranidev** [comment]
Thanks!!
