### ISSUE TITLE
Create a parent child view

### ISSUE THREAD

**Issue by davejal** [amranidev/scaffold-interface#98]
Hi,

I need help to create a view like [https://support.content.office.net/en-us/media/8d712f52-0c4e-4a04-9ffa-7c04cfd75905.jpg](url)

The main form has the parent and the subform has the child records.

Where do I begin?

**Comment by amranidev** [comment]
The image is not available!!
Feel free to create your own blade layouts, check laravel docs ([Blade template](https://laravel.com/docs/5.3/blade))
